### ISSUE TITLE
Conflicts with Steam Controller

### ISSUE THREAD

**Issue by michaldybczak** [bitrig/bitrig-xenocara#1]
If that package is identical with the one available in AUR, in certain situations it conflicts with AUR.
Here is a thread:

https://steamcommunity.com/app/353370/discussions/0/364041432727678852/

I had exactly the same problem on Skyrim. After few minutes mouse was going up by itself and I wasn't able to control it neither in game or in desktop. Shutting down steam controller was fixing it for a moment. Uninstalling xf86-input-joystick solves the problem permanently.

**Comment by jcvernaleo** [comment]
@michaldybczak I think you might have the wrong repo for this.  This is not an Arch Linux thing, it is the X system for Bitrig (forked from OpenBSD's X server).

**Comment by michaldybczak** [comment]
Ah, sorry to bother you then. Your package was top search result on google so I thought I got to the right place ;).
